### ISSUE TITLE
Add a check for flush_rewrite_rules use

### ISSUE THREAD

**Issue by emiluzelac** [Otto42/theme-check#104]
I don't think that there is a real reason why `flush_rewrite_rules` would be needed for themes. Usual case scenario is probably a CPT, but we don't allow them.

Your thoughts?

**Comment by Otto42** [comment]
I can think of a few possible cases, maybe. But, honestly, are themes actively trying to use this in the directory in ways that we need to prevent? I'd rather add something like this as a reaction to existing submissions than pro-actively block it in advance. Maybe somebody has a valid use.

In other words, if this is an actual problem, then sure, block it. Otherwise, why worry?

**Comment by emiluzelac** [comment]
Fair enough :)
