### ISSUE TITLE
No disabling of the admin toolbar [Required]

### ISSUE THREAD

**Issue by grappler** [Otto42/theme-check#127]
Check for `add_filter('show_admin_bar', '__return_false');` and `show_admin_bar(false)`

**Comment by websupporter** [comment]
might also need to check the stylesheets for
`#wpadminbar{display:none;}`

and similar

**Comment by grappler** [comment]
Possible regex: `(add_filter\(.*(?>"|')show_admin_bar(?>"|').*\);)|(show_admin_bar\(.*false.*\);)|(#wpadminbar)`
https://regex101.com/r/pF6vK1/1

We could run the CSS check on only CSS files.

**Comment by websupporter** [comment]
I just checked for 
`show_admin_bar( false ) ;`

You see the space between the function and the semicolon. It would match if we get rid of the semicolons in the regex:

`(add_filter\(.*(?>"|')show_admin_bar(?>"|').*\))|(show_admin_bar\(.*false.*\))|(#wpadminbar)`

**Comment by websupporter** [comment]
But to finally screw things:

`show_admin_bar( do_not_show_me() );
function do_not_show_me(){
	return false;
}`

**Comment by grappler** [comment]
There are loads of ways around the checks. We want to catch only those who are unaware of the requirements.

**Comment by websupporter** [comment]
ah ok. *reliefed* :)

**Comment by websupporter** [comment]
Can't we just say: you are not allowed to use `show_admin_bar(`?

What reason should someone have, to use this in a theme anyway?

**Comment by websupporter** [comment]
So, I was playing around a bit with the regex to see, if it could be a bit improved. I think some changes are good, others maybe more playground (like the `$GLOBALS`-part).

So I use more `(\s*)` since we don't want to loose some, just because of different coding styles for the same operation

```
show_admin_bar( false )
show_admin_bar (false)
show_admin_bar (
	false
)

add_filter ( "show_admin_bar" , "__return_false" );
add_filter( "show_admin_bar" , "__return_false" );
add_filter("show_admin_bar" , "__return_false");

add_filter(
	"show_admin_bar",
	"__return_false"
);
```


And I tried to capture somehow the `$GLOBALS` since `$show_admin_bar` is a global variable. I think I get almost everything but not the basic `$show_admin_bar` (or, we just disable `$show_admin_bar` at all).

My regex looks like this:
`(add_filter(\s*)\((\s*)("|')show_admin_bar("|')(\s*)(.*))|(([^\S])show_admin_bar(\s*)\((.*))|(#wpadminbar)|(global\s(.*)\$show_admin_bar)|(\$GLOBALS\[(\s*)('|")show_admin_bar('|")(\s*)\])`

https://regex101.com/r/aZ6bK7/1

Maybe this is a bit to heavy. But otherwise I would have played Sudoku :1234:

**Comment by Otto42** [comment]
Is this one ready to merge at this time?

**Comment by grappler** [comment]
#138 looks fine to me. It does the basic checks. We can always improve on it in the future.
