### ISSUE TITLE
Include a text domain in style.css [Required]

### ISSUE THREAD

**Issue by grappler** [Otto42/theme-check#130]
Check style.css if `Text Domain:` is set correctly.

**Comment by websupporter** [comment]
> My ideas was also to check if the theme is using the the correct texdomain
https://github.com/Otto42/theme-check/pull/135#issuecomment-200241149

Hmmm... So, if I understand this right, you do also want to check if in `_e( 'text', 'text-domain' )` the `text-domain` matches with the `Text Domain:` in the _style.css_?

I guess, we would just rule this out (since: _who is doing this?_), but this popped up in my mind:
```
<?php
define( 'SLUG_TD', 'i-have-a-very-long-text-domain-and-dont-want-to-repeat-it-always' );
_e( 'hi everyone', SLUG_TD );
?>
```

**Comment by grappler** [comment]
For language pack to work correctly the text domain must match the theme slug. So it if the theme is call "Superman vs Batman" then the text domain must be "superman-vs-batman".

By defining the text domain in the style.css the theme description can still be translated even if the theme is not active.

Constants and variables are not allowed for themes. There is already a check for that.

**Comment by Otto42** [comment]
If anybody wants to add a further check to make sure the domain matches the slug, then a PR would be happily accepted.
