### ISSUE TITLE
Check for deprecated functions in a class

### ISSUE THREAD

**Issue by grappler** [Otto42/theme-check#140]
We have a special case here where the function in a class is being replaced by a function with the same name outside the class.

[WP_Customize_Nav_Menus_Panel::wp_nav_menu_manage_columns()](https://developer.wordpress.org/reference/classes/wp_customize_nav_menus_panel/wp_nav_menu_manage_columns)

The code for the deprecated functions can be seen here: https://github.com/Otto42/theme-check/blob/master/checks/deprecated.php

**Comment by Otto42** [comment]
For at least one previous case, I simply stopped checking for that function name, since I couldn't find any themes using that deprecated function to start with, so it seemed edge case.

https://github.com/Otto42/theme-check/commit/0ef5f1efa1b70a3350c527ffb7116e3157cbe27e

Theme Check does not have to be totally complete. Just useful as a tool.

**Comment by grappler** [comment]
Completely agree. Just needs to be a conscious decision :smile: Closing
