### ISSUE TITLE
INFO: Non-printable characters were found in the functions.php file. You may want to check this file for errors.

### ISSUE THREAD

**Issue by tenman** [Otto42/theme-check#51]
enhance request.

tested with Raindrops theme.

https://wordpress.org/themes/raindrops/

```
Line 6431: if ( preg_match_all( '/(https?:\/\/)([-_.!��*\'()a-zA-Z0-9;\/?:@&=+$,%#]+)/iu', $text, $matches, PREG_SET_ORDER ) ) {
Line 8097: return preg_replace_callback( '|>([-_.!��*\'()a-zA-Z0-9;\/?:@&=+$,%#]{30,})<|', 'raindrops_add_wbr_content_long_te
```
I'm　using tilde in regex.

If, I want you to tolerate possible tilde

Thank you.

**Comment by Otto42** [comment]
INFO checks are there for your benefit. They're not errors, or warnings, they're informational in nature. The check is there because you can introduce characters that break sites by accident using some editors. 

If the INFO message shows up and you know that that character is supposed to be there, then you can ignore it. However, when it shows up and you don't know why the character is there, then you should investigate it.

I see no real reason to modify this check for this case. It doesn't affect anything, and there is an option to Suppress INFO checks if it really bothers you. However, I recommend that you leave the checks there and read them. Many people have accidentally been locked out of sites because of their editors adding UTF-8 BOM characters to the beginning of their files.
