### ISSUE TITLE
Can we allow file_get_contents

### ISSUE THREAD

**Issue by grappler** [Otto42/theme-check#55]
I read your thoughts on using wp_filesystem http://ottopress.com/2011/tutorial-using-the-wp_filesystem/

The reason I ask is some frameworks use it to load a json file. e.g. https://github.com/aristath/kirki/blob/master/includes/Fonts/FontRegistry.php#L256

As it is only reading and not writing a file do we have the same security risks?

Could we allow `file_get_contents()` in themes?

**Comment by Otto42** [comment]
The file_get_contents function isn't disallowed for the WP_Filesystem reasons, as such, but because malware authors often use it for malicious code. Many hosting systems have the "allow_url_fopen" parameter enabled by default, so file_get_contents can actually get the contents of an HTTP connection, and then do things like execute it and such.

Given the use case, eliminating this check may be reasonable, as long as we have sufficient additional checks to still detect these common forms of malware. You should discuss this with the theme-review-team, see what the general consensus is.

**Comment by aristath** [comment]
Thanks for the insights!

Already fixed in the plugin :+1:

**Comment by grappler** [comment]
I suppose it just easiest to use `wp_filesystem` and create extra issues. Thanks @Otto42 for your comments.
