### ISSUE TITLE
False Positive for sanitize_callback when using Options API

### ISSUE THREAD

**Issue by chipbennett** [Otto42/theme-check#60]
Theme Check output:
`
REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
`

Normally, this would be accurate. Adding `sanitize_callback` to `$wp_customize->add_setting()` is required, when using the default option type, `theme_mod`.

However, when using `'type' => 'option'`, with a valid `sanitize_callback` added to the `register_setting()` call, the `sanitize_callback` is not required in `$wp_customize->add_setting()`.

Solution: check for `sanitize_callback` in the correct location:

1. If `'type' => 'theme_mod'`, then use the current check
2. If `'type' => 'option'`, then check for `register_setting()` call, and check for third parameter, `'sanitize_callback'`.

**Comment by chipbennett** [comment]
Thinking about this one some more. You'll also want to account for Child Theme extension of Options API usage in a parent Theme. So, the sanitization callback could be either the one declared in `register_setting()`, or it could be in `$wp_customize->add_setting()`, for Child Theme-added options.

Perhaps it would just be easiest to check for `sanitize_callback` in both places, and only output a required notice if not found in either?

**Comment by Otto42** [comment]
Realistically, it doesn't make a whole lot of sense to use register_setting if you're only using the settings in the customizer, I think.

The register_setting function is specifically needed for creating a settings page. If themes aren't going to be doing that and will be using the customizer to adjust options instead, then there's no point to calling it. Yes, its sanitize function will indeed be run, however that's the only benefit gained from it. The group and option name are used for the whitelisting of settings, and that's a bit pointless when you have no settings page to set them on.

The customizer's sanitize_callback, on the other hand, runs at a different place. Namely on the POST values being received by the customizer settings. This can be reflected in the returned values to the customizer as well, so if you're using the customizer, you still need to call the sanitize_callback even if you also have a register_setting callback function, because that callback only runs when the data is saved to the database, not when it's just passing through the customizer without being saved. Leaving out a sanitize_callback can lead to self-XSS security issues, possibly allowing for Reflected XSS as well, in some cases.

**Comment by chipbennett** [comment]
So, for all of the people (me included) who have been using Options API for years, and are moving to Customizer API-only integration (i.e. dropping Settings API integration), what is the solution? 

Sure, you can hook the sanitize callback into `sanitize_option_$option`, but will that prevent the REQUIRED output from Theme Check? If not, this is a showstopper.

**Comment by chipbennett** [comment]
Just confirmed, this is an issue, and will be a false-positive that will block uploads:

```
REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.
```

Even with including this:
```
add_action( 'sanitize_option_theme_oenology_options', 'oenology_options_validate' );
```

Re-opening, because the issue is a valid false positive. Hooking into the `sanitize_option_$option` is equally valid to passing sanitization callbacks to each instance of `$wp_customize->add_setting()`.

**Comment by chipbennett** [comment]
Apparently, I can't re-open. Please re-open, as this issue needs to be addressed.

The Theme review requirements require proper sanitization, but they do not mandate one form of sanitization (per-setting) over another (all settings). Thus, both methods are valid, and need to be accounted for.

**Comment by chipbennett** [comment]
Okay, so I think I have this sorted. The main issue is that while you can arbitrarily sanitize a select/radio setting (or other setting with a defined list of valid choices), you can't validate using the sanitize_callback, when building controls dynamically from an array of option parameters, because you have no way of passing the valid options to the callback. So, if you have a solution to that, I'm all ears.

I will probably write up a blog post on Make/Themes for this, because I assume that others making a conversion will run into the same issue.

**Comment by chipbennett** [comment]
I want to make sure I understand/explain this properly:

> The customizer's sanitize_callback, on the other hand, runs at a different place. Namely on the POST values being received by the customizer settings. This can be reflected in the returned values to the customizer as well, so if you're using the customizer, you still need to call the sanitize_callback even if you also have a register_setting callback function, because that callback only runs when the data is saved to the database, not when it's just passing through the customizer without being saved. Leaving out a sanitize_callback can lead to self-XSS security issues, possibly allowing for Reflected XSS as well, in some cases.

So, are you saying that defining `register_setting( $option_group, $option, $sanitize_cb )`, and then hooking `$sanitize_cb` into `sanitize_option_$option` (e.g. `add_action( 'sanitize_option_' . $option, $sanitize_cb )`), will not sanitize POST values being received by the customizer settings?

**Comment by Otto42** [comment]
Okay, I'm confused by your confusion here, so let me attempt to clarify:

If you're using the customizer only, and don't actually have a settings page any more, then there's no actual reason to call register_settings() at all. You can remove the register_settings() call entirely.

Does that make any sense? How can I clarify this better? Why are you trying to perform double sanitization? What are you using the register_settings call for?

**Comment by Otto42** [comment]
To further clarify: Having a proper sanitize_callback in the Customizer *is absolutely required under all circumstances, period*. It does not make any difference what other sanitization you have.

**Comment by Otto42** [comment]
> you can't validate using the sanitize_callback, when building controls dynamically from an array of option parameters, because you have no way of passing the valid options to the callback

The callback can call other functions to retrieve whatever the list of valid options are. It's running in WordPress. It has access to everything there.

**Comment by chipbennett** [comment]
We are requiring use of the Customizer API, in lieu of the Settings API, to
expose Theme options to the user. As far as I am aware, we are NOT
requiring use of the Theme Mods API, in lieu of the Options API, to
store/retrieve Theme options.

Consider those developers who implemented Settings API before the
Customizer API even existed. Some (like me) may have added the Customizer
API integration long ago, but left the Settings API implementation intact.
Some may only now be adding Customizer API implementation. Almost all of
those developers will have used the Options API, and not the Theme Mods
API. Thus, all will have a `register_setting()` call.

For such developers, it makes no sense to move from Options API to Theme
Mods API. Doing so would have adverse impact to existing users, because
they would lose their existing settings (or else, some extensive script
would have to be used to port Options API-stored settings to Theme Mods
API-stored settings). So, the `register_setting()` call needs to remain, in
order to pair the Options API with the Customizer API.

Now, if you're saying that this call:
```
add_action( 'sanitize_option_theme_oenology_options',
'oenology_options_validate' );
```
...can replace this call?
```
register_setting( 'theme_oenology_options', 'theme_oenology_options',
'oenology_options_validate' );
```
Then I'm following you. But again: is one required to be used in lieu of
the other?

**Comment by Otto42** [comment]
No, I'm saying that neither one is good enough if you're using the Customizer.

First, the register_setting function really just sets the sanitize_option_* filter for you, so yes, functionally those are identical.

Now, the sanitize_option_* filter is called from the sanitize_option() function. The sanitize_option() function is called from a number of places, mainly add_option() and update_option() and similar. These all run when the option is added to or updated in the database.

But the Customizer does not always update the database. When I make a change on the Customizer screen, then the values from my settings are sent back into WordPress via $_POST. The customizer then does it's thing and returns a new view of my webpage with those new options shoved into place using filters. But what is important here is that those options *are not saved* at this time. They never run through update_option(). They don't run through sanitize_option(). And they never run through the sanitize_option_* filter.

This is why they are insufficient. That filter only protects you against saving invalid options to the database. It does not protect you against Reflected XSS attacks. The Customizer's sanitize_callback is required because it runs on that POST data which isn't being saved, but which is being reflected back to you in the resulting preview pane.

**Comment by chipbennett** [comment]
I'm with you on the sanitization within the Customizer. That's a separate
issue and can be handled separately. I've handled it by adding pure
sanitization callbacks to $wp_customize->add_setting()`. It's still not
possible to do validation that way (when building settings and controls
dynamically from an array of settings parameters), but that's handled on
save using the pre-existing all-settings sanitization callback.

Your part in italics was what I wasn't getting initially when I opened the
ticket.

**Comment by Otto42** [comment]
> It's still not possible to do validation that way (when building settings and controls dynamically from an array of settings parameters),

I'm really not following your logic here. The function that you pass to the sanitize_callback parameter can call other functions too, you know. If you can dynamically build the controls, then you have the data needed to validate them there too.

**Comment by Otto42** [comment]
BTW, the function that you pass to sanitize_callback actually gets 2 parameters passed to it. The first parameter is the value, and the second parameter is the WP_Customize_Setting object itself. If it's something like a radio control or anything that has a fixed set of parameters, then that object will have those valid parameters in it.

**Comment by chipbennett** [comment]
The data that gets passed to `sanitize_callback` inside
`$wp_customize->add_setting()` is just the setting value. It's not an
associative array, with a key to use to reference the setting name - at
least, as far as I can tell, it isn't.

So, if you have a select, and it returns `'blue'`, it is the string,
`'blue'`, that gets passed to the sanitize callback. How can that callback
know if that string applies to `'color_option_1'` or `color_option_2'` (for
example)?

Or, for a better example from my own Theme, look at the various layout
settings (defaults for static pages, single posts, archive pages). How
would the sanitize callback for the setting for any one of those know which
option to which it applied?

https://github.com/chipbennett/oenology/blob/master/functions/options-config.php#L202

If there's something that I'm missing here, I'm all ears.

**Comment by Otto42** [comment]
Think we cross-commented. See my comment above. You do get the data you need, as a second parameter.

**Comment by chipbennett** [comment]
And that was the something I was missing. Holy crap. Mind = blown.
