### ISSUE TITLE
REQUIRED: Themes should use add_theme_page() for adding admin pages.

### ISSUE THREAD

**Issue by dovy** [Otto42/theme-check#65]
If a class, namely Redux, possesses the ability to add_menu_page, but it is not used as a developer for .org, does it have to be flagged? I'd like this not to fail the forthcoming theme-check errors.  ;)

**Comment by dovy** [comment]
Makes me want to use #62, hah.

**Comment by Otto42** [comment]
I don't understand. Using add_theme_page is allowed.

**Comment by dovy** [comment]
I meant add_menu_page.  ;)

**Comment by dovy** [comment]
Namely, with Redux you can make your own menu items or place under an existing item. WP.org users are instructed not to use the add_menu_page function as it's not permitted. Theme Check still flags it.  :(

**Comment by Otto42** [comment]
That's a question for the theme review team. Theme-check cannot tell context or whether code is used or not. It doesn't run the code, it just reads it.

**Comment by justintadlock** [comment]
The reason for this check is that themes were adding menus all over the place in the admin.  If you can imagine it, it was happening.  This check makes sense because it fixes what was a widespread issue.

I imagine that you'd need to find an alternative solution to present to TRT that handles the primary issue but allows your code to go through.

Just thinking ahead:  The response you get might be something along the lines of *themes shouldn't include unused code*.  As I'm not really familiar with Redux, is it possible to separate this in some fashion for theme/plugin authors?

Off the top of my head, allow plugin devs to do something like:

	function pluginname_config_settings_page() {

		add_menu_page(
			$page_title,
			$menu_title,
			$capability,
			$menu_slug,
			'redux_callback_for_settings_page'
		);
	}

It might be a bit more complex than that; I don't know.  Just throwing one idea out there.

**Comment by Otto42** [comment]
At this time, the TRT disallows use of add_*_page other than add_theme_page, to keep theme admin pages in the Appearance menu. If this changes in the future, then we can reconsider altering this check.
