### ISSUE TITLE
Check for Themes Registering Alternate jQuery Version

### ISSUE THREAD

**Issue by devinsays** [Otto42/theme-check#70]
Just ran across this in a review:

```
//move jquery to the footer 
wp_deregister_script('jquery');  
wp_register_script('jquery', get_template_directory_uri() . '/js/vendor/jquery.js', false, '1.11.3', false); 
```

**Comment by Otto42** [comment]
If you have a suggestion for how to detect this in a sane manner, I'm all ears. Maybe check for the deregister?

**Comment by grappler** [comment]
Checking for deregister/dequeue jQuery would be a good start.

**Comment by wpdev101** [comment]
I'm not all that good with regex so please excuse me if I'm doing something dumb.

http://pastie.org/10379790

First it checks if **wp_enqueue_script( 'jquery',** has been called ( with the comma ), meaning they also have the URL parameter which I don't see a valid reason for in case of jQuery enqueue.

If that's not found it checks if **wp_register_script( 'jquery'** and again, I don't see a valid reason for that either.

The error message I used is not quite good so that would need to be changed.

**Comment by Otto42** [comment]
Checking for register is reasonable. Not sure about enqueue though. Pretty sure that you can't do an enqueue for a script with a url when it's already been registered. Need to test that, actually.

**Comment by WPCanyon** [comment]
Yeah, that's correct. Just tested, the URL parameter in enqueue is not relevant if the script has been registered already.

However if the script has been deregistered then the enqueue would function normally.

So they can deregister it and then go straight to enqueue instead of registering first. Without the enqueue check they'll pass the test.

**Comment by wpdev101** [comment]
Yeah, that's correct. Just tested, the URL parameter in enqueue is not relevant if the script has been registered already.

However if the script has been deregistered then the enqueue would function normally.

So they can deregister it and then go straight to enqueue instead of registering first. Without the enqueue check they'll pass the test.

**Comment by Otto42** [comment]
I cannot think of any valid reason for a theme to deregister a core script.

**Comment by wpdev101** [comment]
Yeah, I'm pretty sure there's none. Plugins rely on those core files as well so that would break them. 

Ok, I think it' safe to say doing a check for **wp_deregister_script('jquery')** is enough.

**Comment by devinsays** [comment]
Nice work. Thanks @carolinan.
