### ISSUE TITLE
theme check for customizer sanitize_callback

### ISSUE THREAD

**Issue by tenman** [Otto42/theme-check#81]
I've noticed a strange behavior of the theme check of function.

for example. use twenty fifteen.

customize.php line 26

```
	$wp_customize->add_setting( 'color_scheme', array(
		'default'           => 'default',
		'sanitize_callback' => 'twentyfifteen_sanitize_color_scheme',
		'transport'         => 'postMessage',
	) );
```
change below

```
	$wp_customize->add_setting( 'color_scheme', array(
		'default'           => 'default',
		'sanitize_callback' => 'twentyfifteen_abcdefg',
		'transport'         => 'postMessage',
	) );
```

function twentyfifteen_abcdefg() , Such a function does not exist

but theme check plugin not say error.

WP_DEBUG not say error.

Theme works properly ... why?

**Comment by Otto42** [comment]
Because it's a callback function. Essentially, it's implemented as a WordPress filter. The filter system checks for function existence before calling the function. If the function doesn't exist, then it does not get called.

Theme check doesn't check that your code is *correct*, just that it isn't obviously missing something. Theme check will not protect you against maliciousness or stupidity. It's a tool to help developers develop, not to find and prevent errors.
