### ISSUE TITLE
Throws warnings on check (copy from)

### ISSUE THREAD

**Issue by lordspace** [Otto42/theme-check#99]
notice
```Notice: Undefined offset: 2 in C:\Copy\Dropbox\cloud\projects\clients\myfakesite.com.com\htdocs\wp-content\plugins\theme-check\checks\textdomain.php on line 82```

fix

```if (!empty($this->rules[$func][$args_count]) && $this->rules[$func][$args_count] == 'domain') .... ```

This was originally submitted in: https://wordpress.org/support/topic/throws-warnings-on-check?replies=1

**Comment by Otto42** [comment]
The fix actually needs to be made in your theme. Somewhere, you are calling a translation function with too many arguments.

Additionally, this issue has already been fixed in theme-check here, it just has not been released yet:
https://github.com/Otto42/theme-check/commit/b79f797b3922eebbda22fe714c6bc13f9f2c1265

**Comment by lordspace** [comment]
Otto, that was the notice the theme check plugin gave me when I was testing the theme which Trac assigned to me on contributor's day at WordCamp Sofia (held a few days ago).
